name: offlag
description: "Ona Alisher my teper zaprechenkf"
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  flutter_v2ray_plus: ^1.0.19
  flutter_secure_storage: ^9.2.2
  package_info_plus: ^8.0.2
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  window_manager: ^0.3.9
  video_player: ^2.9.2
  animations: ^2.0.11
  url_launcher: ^6.3.0
  path_provider: ^2.1.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/capsule.svg
    - assets/logo/knob.svg
    - assets/logo/logo_h.svg
    - assets/anim/logo.webp
    - assets/anim/logo_lastframe.png
  fonts:
    - family: PTSans
      fonts:
        - asset: assets/fonts/PTSans-Bold.ttf
          weight: 700
